when_modified:
  file_patterns: []

dirs:
  'rfds/**/index*':
    tags: ['rfd']
    when_modified:
      file_patterns: ['${DIR}/*']

workflows:
  - tag_query: rfd
    lock_policy: none
    engine:
      name: custom
      # If plan runs successfully, report no changes.  We are only really
      # interested in the workflows section being called.
      plan: ['bash', '-c', 'echo "{}" > $TERRATEAM_PLAN_FILE; exit 2']
    plan:
      - type: run
        cmd: ['${TERRATEAM_ROOT}/bin/verify-status']
      - type: plan

cost_estimation:
  enabled: false
